name: Deploy JupyterBook to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master' if that's your primary branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To allow committing _build folder if needed, or to interact with Pages
      pages: write # To allow deployment to GitHub Pages
      id-token: write # Needed for OpenID Connect authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a compatible Python version

      - name: Install Jupyter Book and dependencies
        run: |
          pip install jupyter-book sphinx-book-theme myst-parser
          pip install -r requirements.txt # If you have a requirements.txt

      - name: Build Jupyter Book
        run: |
          jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html # This is where Jupyter Book puts the built website

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}